name: factormodel
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1=hb4e282d_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.0=hd04f020_2
  - openssl=1.0.2o=h26aff7b_0
  - pip=10.0.1=py36_0
  - python=3.6.5=hc167b69_1
  - readline=7.0=hc1231fa_4
  - setuptools=39.1.0=py36_0
  - sqlite=3.23.1=hf1716c9_0
  - tk=8.6.7=h35a86e2_3
  - wheel=0.31.0=py36_0
  - xz=5.2.3=h727817e_4
  - zlib=1.2.11=hf3cbc9b_2
  - pip:
    - appnope==0.1.0
    - backcall==0.1.0
    - chardet==3.0.4
    - click==6.7
    - cycler==0.10.0
    - dash==0.21.1
    - dash-auth==1.0.1
    - dash-core-components==0.23.0
    - dash-html-components==0.11.0
    - dash-renderer==0.13.0
    - decorator==4.3.0
    - flask==1.0.2
    - flask-compress==1.4.0
    - flask-seasurf==0.2.2
    - idna==2.6
    - ipykernel==4.8.2
    - ipython==6.3.0
    - ipython-genutils==0.2.0
    - itsdangerous==0.24
    - jedi==0.12.0
    - jinja2==2.10
    - jsonschema==2.6.0
    - jupyter-client==5.2.3
    - jupyter-core==4.4.0
    - kiwisolver==1.0.1
    - markupsafe==1.0
    - matplotlib==2.2.2
    - nbformat==4.4.0
    - numpy==1.14.2
    - pandas==0.20.3
    - parso==0.2.0
    - pexpect==4.5.0
    - pickleshare==0.7.4
    - plotly==2.7.0
    - prompt-toolkit==1.0.15
    - psycopg2==2.7.5
    - ptyprocess==0.5.2
    - pygments==2.2.0
    - pyparsing==2.2.0
    - python-dateutil==2.7.2
    - pytz==2018.4
    - pyzmq==17.0.0
    - requests==2.18.4
    - retrying==1.3.3
    - scikit-learn==0.18.1
    - scipy==1.1.0
    - seaborn==0.8.1
    - simplegeneric==0.8.1
    - six==1.11.0
    - sqlalchemy==1.2.7
    - tornado==5.0.2
    - traitlets==4.3.2
    - urllib3==1.22
    - wcwidth==0.1.7
    - werkzeug==0.14.1
    - xlrd==1.1.0
    - gunicorn==19.7.1
    - pytest==3.5.1
prefix: /Users/Jeppe/anaconda3/envs/seahorse
